definitions:
  model.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      traceID:
        type: string
    type: object
  model.PatientProfile:
    properties:
      address:
        type: string
      city:
        type: string
      createdAt:
        type: string
      dateOfBirth:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      mobile:
        type: string
      phone:
        type: string
      profession:
        type: string
      province:
        type: string
      updatedAt:
        type: string
      zipCode:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: cris@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a crixo cample
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /patients:
    get:
      consumes:
      - application/json
      description: Return a paged set of patient profiles w/ the total number of available
        patients
      operationId: patients-profile-find
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              description: Total number of records w/o pagination
              type: int
          schema:
            items:
              $ref: '#/definitions/model.PatientProfile'
            type: array
      summary: Get paged patient profiles
      tags:
      - patients
    post:
      consumes:
      - application/json
      description: Create Patient Profile
      operationId: patients-profile-create
      parameters:
      - description: Create new patient profile
        in: body
        name: patientProfile
        required: true
        schema:
          $ref: '#/definitions/model.PatientProfile'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PatientProfile'
            type: object
      summary: Create Patient Profile
      tags:
      - patients
  /patients/{id}:
    put:
      consumes:
      - application/json
      description: Update Patient Profile
      operationId: patients-profile-update
      parameters:
      - description: Update an existing patient profile
        in: body
        name: patientProfile
        required: true
        schema:
          $ref: '#/definitions/model.PatientProfile'
          type: object
      - description: Patient profile identifier that has to match w/ the identifier
          within the body contract
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PatientProfile'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
            type: object
      summary: Update Patient Profile
      tags:
      - patients
swagger: "2.0"
